language: generic

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t mytag .

script:
  - docker run -e CI=true mytag npm run test
# deploy:
#   provider: elasticbeanstalk
#   region: "eu-west-1"
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-eu-west-1-666136143444"
#   bucket_path: "docker"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
